### PR TITLE
Automated tests for bslib's new card(), value_box(), and layout_column_wrap()

### PR DESCRIPTION
**Pull request by cpsievert**

### CODE REVIEW

**Comment by cpsievert** [comment]
@schloerke Is there a way to add `_snaps` prior to merging or do we have to check them afterwards?

**Comment by schloerke** [comment]
While sitting in your PR branch... `shinycoreci::fix_snaps()`

**Comment by cpsievert** [comment]
@schloerke I didn't quite follow wait you said earlier today about adding dependencies "manually", so I just added `{gt}` as a dependency in [299a402](https://github.com/rstudio/shinycoreci/pull/132/commits/299a4021b07efe57732317d8602ae13624b50f47)

What's the right way to do this?

**Comment by cpsievert** [comment]
Merging a bit early (i.e., prior to approval) so that we have results with the development version of htmlwidgets. 

@schloerke it's worth noting that we don't necessarily need the development version of gt (I added it to `R/data-shinyverse.R` just to get the screenshots), so let me know if you'd prefer to revert that.

**Pull request merged**
