### PR TITLE
docker(ssp): Add more cases for aws build machine envvar

### PR DESCRIPTION
**Pull request by gadenbuie**
Trying to fix failing builds: https://github.com/rstudio/shinycoreci/actions/runs/6710699582

### CODE REVIEW

**Comment by schloerke** [comment]
@gadenbuie From https://posit.co/download/shiny-server/#tab-content-1, the aws link should stay at 18.04. 

I saw from a prior error that `libssl1.1` was missing. We should install that in the base docker image for jammy.
Related: https://askubuntu.com/questions/1424442/libssl1-1-is-deprecated-in-ubuntu-22-04-what-to-do-now

**Comment by gadenbuie** [comment]
> @gadenbuie From [posit.co/download/shiny-server/#tab-content-1](https://posit.co/download/shiny-server/#tab-content-1), the aws link should stay at 18.04.

What's weird is that: 1) I tried all the links and they worked with the differentiated AWS_BUILD_MACHINE; 2) the jammy docker images are building successfully now.

**Comment by schloerke** [comment]
"🤦‍♂️"
- Documentation

**Comment by gadenbuie** [comment]
Every once in a while I get bitten by my "try it and see if it works before reading the docs" approach, but not today 😄

**Pull request merged**
